In [1]:
import numpy as np

# Creating arrays
x = np.array([100, 200, 300])
y = np.array([100, 800, 900])
z = np.array((44, 77, 99))
x1 = np.array([[1, 2, 3], [3, 5, 6], [9, 7, 9]])
x2 = np.array([[[4, 5, 6], [7, 8, 9], [1, 6, 7]]])
z1 = np.array(67)
w = np.array([[[1, 3, 4], [3, 5, 6]], [[1, 6, 9], [3, 5, 6]]])


In [2]:
# Checking properties
print(np.__version__)  # Display NumPy version
print(z.ndim)  # Display dimension of z
print(z1.ndim)  # Display dimension of z1
print(x1.ndim)  # Display dimension of x1
print(x2.ndim)  # Display dimension of x2


1.26.2
1
0
2
3


In [3]:
# Accessing elements
print(z)  # Display array z
print(z[2])  # Display the third element of z
print(x1)  # Display array x1
print(x1[2, 1])  # Display element at the third row and second column of x1
print(w)  # Display array w
print(w[1, 0, 2])  # Display element at the second array, first row, and third column of w


[44 77 99]
99
[[1 2 3]
 [3 5 6]
 [9 7 9]]
7
[[[1 3 4]
  [3 5 6]]

 [[1 6 9]
  [3 5 6]]]
9
