In [1]:
import numpy


In [2]:
x=numpy.array([100,200,300])
x

array([100, 200, 300])

In [3]:
print(x)

[100 200 300]


In [4]:
import numpy as np


In [6]:
y=np.array([100,800,900])
y

array([100, 800, 900])

In [7]:
print(np.__version__)

1.26.2


In [9]:
z=np.array((44,77,99))
print(z)

[44 77 99]


In [10]:
x1=np.array([[1,2,3],[3,5,6],[9,7,9]])
print(x1)

[[1 2 3]
 [3 5 6]
 [9 7 9]]


In [11]:
x2=np.array([[[4,5,6],[7,8,9],[1,6,7]]])
print(x2)

[[[4 5 6]
  [7 8 9]
  [1 6 7]]]


In [12]:
z1=np.array(67)
print(z1)

67


In [13]:
print(z.ndim)

1


In [15]:
print(z1.ndim)

0


In [16]:
print(x1.ndim)

2


In [17]:
print(x2.ndim)

3


In [18]:
print(z)

[44 77 99]


In [19]:
print(z[2])

99


In [20]:
print(x1)

[[1 2 3]
 [3 5 6]
 [9 7 9]]


In [23]:
print(x1[2,1])

7


In [30]:
w=np.array([[[1,3,4],[3,5,6]],[[1,6,9],[3,5,6]]])
print(w)
print(w.ndim)

[[[1 3 4]
  [3 5 6]]

 [[1 6 9]
  [3 5 6]]]
3


In [31]:
print(w[1,0,2])

9
